services:
  dev:
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
    environment:
      WEB_SERVER_PORT: ${WEB_SERVER_PORT}
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./static
          target: /app/static
          action: sync
        - path: ./tests
          target: /app/tests
          action: sync
