services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: database
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:7.4-alpine3.20
    container_name: cache
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
