FROM node:20.17.0-slim AS builder
WORKDIR /app
COPY . .
RUN npm install -g pnpm@9 && \
    pnpm install

FROM node:20.17.0-alpine3.20
WORKDIR /app
COPY --from=builder /app .

EXPOSE ${SERVER_PORT}
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0"]
